#!/bin/bash

WALLPAPERS_DIR="$HOME/Pictures/Wallpapers"

WALLPAPER=$(find "$WALLPAPERS_DIR" -type f | shuf -n 1)

# Set the wallpaper using swaybg
pkill swaybg
swaybg -i "$WALLPAPER" -m fill &

# Generate new colors with wal
wal -i "$WALLPAPER"

killall waybar
waybar &

notify-send "Wallpaper changed!" "$WALLPAPER"
